# Generated by Django 3.0.11 on 2021-02-15 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_auto_20210214_1705"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePermissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("CR", "Creator"), ("CO", "Collaborator")],
                        default="CR",
                        max_length=2,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_users",
                        to="games.Game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
