# Generated by Django 3.0.11 on 2021-02-01 02:23

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_question_details"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                ("submitted", models.BooleanField(default=False)),
                ("points", models.FloatField(null=True, blank=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="games.Question",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="teams.Team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "question")},
            },
        ),
    ]
