# Generated by Django 3.0.11 on 2021-02-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamanswer',
            options={'ordering': ('question_id', 'submitted_at')},
        ),
        migrations.AddField(
            model_name='teamanswer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
