# Generated by Django 3.0.11 on 2021-02-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20210211_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('game', 'score', 'name')},
        ),
    ]
