# Generated by Django 3.0.11 on 2021-02-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210214_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('game', '-score', 'name')},
        ),
    ]
