# Generated by Django 3.0.11 on 2021-01-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_ordering_to_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
