# Generated by Django 3.0.11 on 2021-02-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_question_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game', to='games.Round'),
        ),
    ]
