# Generated by Django 3.0.11 on 2021-02-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_round_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='current',
        ),
        migrations.RemoveField(
            model_name='round',
            name='state',
        ),
    ]
