# Generated by Django 3.0.11 on 2021-02-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_auto_20210203_0103"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
