# Generated by Django 3.0.11 on 2021-02-11 21:57

from django.db import migrations, models
import zoom_trivia.games.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=zoom_trivia.games.helpers.rename
            ),
        ),
    ]
