# Generated by Django 3.0.11 on 2021-02-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_auto_20210211_2157"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="link_display",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
