# Generated by Django 3.0.11 on 2021-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210213_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
