# Generated by Django 3.0.11 on 2021-02-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_round_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="lightning",
            field=models.BooleanField(default=False),
        ),
    ]
