# Generated by Django 3.0.11 on 2021-02-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20210214_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
