# Generated by Django 3.0.11 on 2021-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_in_question',
            field=models.BooleanField(default=True, verbose_name='View in question'),
        ),
    ]
