# Generated by Django 3.0.11 on 2021-03-11 03:03

from django.db import migrations, models
import zoom_trivia.games.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_question_image_in_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to=zoom_trivia.games.helpers.rename
            ),
        ),
    ]
